version: '3'
services:
  cadocuir:
    image: svelte-docker-node
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadocuir.rule=Host(`www.cadocuir.com`, `cadocuir.com`)"
      - "traefik.http.routers.cadocuir.entrypoints=http"
      - "traefik.http.routers.cadocuir-secure.rule=Host(`www.cadocuir.com`,`cadocuir.com`)"
      - "traefik.http.routers.cadocuir-secure.entrypoints=https"
      - "traefik.http.routers.cadocuir-secure.tls=true"
      - "entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "traefik.http.services.cadocuir.loadbalancer.server.port=3000"
      - "traefik.http.routers.cadocuir.middlewares=redirect-non-www-to-www@file"

networks:
  traefik-net:
   external: true