name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        password: ${{ secrets.PASSWORD }} 
        script: cd /home/guillianv/dev/sveltekit/cadocuir/website && docker compose down && git pull origin master && docker compose up -d --force-recreate --build